use_default_settings: true

general:
  instance_name: "SearXNG Railway"

server:
  secret_key: "9xK3pL2vQ7tA4sM8ZcR1YwF6HnU5bE0D"
  limiter: false
  image_proxy: true
  method: "GET"

valkey:
  url: ${SEARXNG_REDIS_URL}

search:
  safe_search: 0
  default_lang: "en"
  formats:
    - html
    - json

ui:
  default_theme: simple
